### ISSUE TITLE
Bimatchable?

### ISSUE THREAD

**Issue by joelburget** [viercc/matchable#1]
Hi there, I independently discovered something like your `Matchable`, but I'm actually using the `Bifunctor` version. Would you be interested in adding this typeclass to your package?

```haskell
class Bifunctor f => Bimatchable f where
  bimatch :: f a x -> f b y -> Maybe (f (a, b) (x, y))
  bimatch = bimatchWith (fmap Just . (,)) (fmap Just . (,))

  bimatchWith
    :: (a -> b -> Maybe c) -> (x -> y -> Maybe z)
    -> f a x -> f b y -> Maybe (f c z)
```

Note that, to match your `Matchable`, we'd want to add an `Eq2` superclass, though I'm not convinced it's necessary.

**Comment by viercc** [comment]
If there's an use case, I'm open to adding relevant abstractions. I'll add `Bimatchable` in the next version.

`Matchable` has `Eq1` as a superclass because `liftEq` can be implemented using `Matchable` method, like `Applicative` methods can be implemented using `Monad` methods.

I'm going to employ `Eq2` as a superclass of `Bimatchable` and provide `liftEq2Default` to ease implementations of instances. I realize how `Eq2` is rarely needed, but I think requiring `Eq2` is the safer bet than ignoring now and owe a risk of adding it later.

**Comment by joelburget** [comment]
I see you've added this -- thank you! Also, I agree about the `Eq1` / `Eq2` superclasses -- thanks for the explanation.

**Comment by viercc** [comment]
Added documentation to Bimatchable and uploaded to Hackage.
