### ISSUE TITLE
Template haskell auto-deriving?

### ISSUE THREAD

**Issue by joelburget** [viercc/matchable#2]
For my own project I wrote `deriveBimatchable` (like the functions you'd find in [`Data.Bifunctor.TH`](https://hackage.haskell.org/package/bifunctors-5.4.2/docs/Data-Bifunctor-TH.html)). I could adapt it and write `deriveMatchable` as well, if you're interested.

**Comment by viercc** [comment]
Thank you, and I welcome `deriveMatchable` as well. This package already has semi-auto Matchable via Generics, but it's not perfect, as Generic has always been.

I'll be glad if you could send your implementation as a pull request, or publish a package including them.

As a pull request, I prefer `deriveMatchable` and `deriveBimatchable` live in a separate package than `matchable`, likely named `matchable-th`. But it's okay to include them in `matchable`. I'll separate them afterward.

**Comment by viercc** [comment]
@joelburget, thank you for the PR. Since I want more powerful TH generator than your code, I'm extensively rewriting your `Data.Matchable.TH` now. It doesn't mean your contribution was small. I couldn't start writing TH feature without your PR.

The added tests in 9374155 represent my expectation of how much TH generation try hard to generate.

**Comment by viercc** [comment]
1dbe24d8c3c0e2198df3ce0e5d1f680fda9f573d completes immediate goal of TH generator. I'll publish it on Hackage soon.
